package io.casehub.qhorus.api.message;

public enum MessageType {
    /** Ask for information. Receiver must RESPONSE or DECLINE. Carries correlation_id. */
    QUERY,
    /** Ask for action. Receiver must execute then DONE or FAILURE. Carries correlation_id. */
    COMMAND,
    /** Answer a QUERY. Discharges the QUERY obligation. Carries correlation_id. */
    RESPONSE,
    /** Report progress on an open COMMAND. Extends the deadline window. */
    STATUS,
    /** Refuse a QUERY or COMMAND. Requires non-empty content. */
    DECLINE,
    /** Transfer obligation to named target. Target field must be non-null. */
    HANDOFF,
    /** Signal successful completion of a COMMAND. Terminal. */
    DONE,
    /** Signal unsuccessful termination of a COMMAND. Requires non-empty content. Terminal. */
    FAILURE,
    /** Observer-only telemetry. NOT delivered to agent context. */
    EVENT;

    /** Whether this message type appears in agent context (true for all except EVENT). */
    public boolean isAgentVisible() {
        return this != EVENT;
    }

    /** Whether this type carries a correlationId (auto-generated by infrastructure). */
    public boolean requiresCorrelationId() {
        return this == QUERY || this == COMMAND;
    }

    /** Whether this type requires non-empty content. */
    public boolean requiresContent() {
        return this == DECLINE || this == FAILURE;
    }

    /** Whether this type requires a non-null target field. */
    public boolean requiresTarget() {
        return this == HANDOFF;
    }

    /** Whether this is a terminal type (no further messages expected from sender). */
    public boolean isTerminal() {
        return this == HANDOFF || this == DONE || this == FAILURE;
    }
}
