package io.casehub.qhorus.api;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;
import static org.junit.jupiter.api.Assertions.*;

import java.util.UUID;

import jakarta.inject.Inject;

import org.junit.jupiter.api.Test;

import io.casehub.qhorus.runtime.mcp.QhorusMcpTools;
import io.quarkus.test.junit.QuarkusTest;
import io.quarkus.test.junit.TestProfile;

/**
 * Issue #34 — POST /a2a/message:send maps A2A SendMessageRequest to send_message.
 *
 * <p>
 * Three levels of testing:
 * <ul>
 * <li>Unit: field mapping, auto-generated taskId, state returned</li>
 * <li>Integration: request creates a retrievable message in the channel</li>
 * <li>End-to-end: A2A send → message visible via check_messages MCP tool</li>
 * </ul>
 *
 * <p>
 * Note: {@code urlEncodingEnabled(false)} is required for all POST calls to
 * {@code /a2a/message:send} — see A2AResourceDisabledTest for explanation.
 *
 * <p>
 * Refs #34, Epic #32.
 */
@QuarkusTest
@TestProfile(A2AEnabledProfile.class)
class A2ASendMessageTest {

    @Inject
    QhorusMcpTools tools;

    private static final String SEND_PATH = "/a2a/message:send";

    // -----------------------------------------------------------------------
    // Helper
    // -----------------------------------------------------------------------

    private String sendBody(String contextId, String role, String text, String taskId) {
        String taskPart = taskId != null ? "\"taskId\":\"" + taskId + "\"," : "";
        return "{\"message\":{\"role\":\"" + role + "\","
                + taskPart
                + "\"contextId\":\"" + contextId + "\","
                + "\"parts\":[{\"kind\":\"text\",\"text\":\"" + text + "\"}]}}";
    }

    // -----------------------------------------------------------------------
    // Unit — field mapping and response shape
    // -----------------------------------------------------------------------

    @Test
    void sendReturns200WithTaskInSubmittedState() {
        tools.createChannel("a2a-send-1", "Test", "APPEND", null, null, null, null, null, null);

        given()
                .urlEncodingEnabled(false)
                .contentType("application/json")
                .body(sendBody("a2a-send-1", "user", "hello", null))
                .when().post(SEND_PATH)
                .then()
                .statusCode(200)
                .body("task.status.state", equalTo("submitted"));
    }

    @Test
    void sendResponseContainsTaskId() {
        tools.createChannel("a2a-send-2", "Test", "APPEND", null, null, null, null, null, null);

        given()
                .urlEncodingEnabled(false)
                .contentType("application/json")
                .body(sendBody("a2a-send-2", "user", "hello", null))
                .when().post(SEND_PATH)
                .then()
                .statusCode(200)
                .body("task.id", not(emptyOrNullString()));
    }

    @Test
    void sendResponseReflectsContextId() {
        tools.createChannel("a2a-send-3", "Test", "APPEND", null, null, null, null, null, null);

        given()
                .urlEncodingEnabled(false)
                .contentType("application/json")
                .body(sendBody("a2a-send-3", "agent", "work item", null))
                .when().post(SEND_PATH)
                .then()
                .statusCode(200)
                .body("task.contextId", equalTo("a2a-send-3"));
    }

    @Test
    void providedTaskIdIsUsedAsCorrelationId() {
        tools.createChannel("a2a-send-4", "Test", "APPEND", null, null, null, null, null, null);
        String taskId = UUID.randomUUID().toString();

        given()
                .urlEncodingEnabled(false)
                .contentType("application/json")
                .body(sendBody("a2a-send-4", "user", "with explicit task id", taskId))
                .when().post(SEND_PATH)
                .then()
                .statusCode(200)
                .body("task.id", equalTo(taskId));
    }

    @Test
    void absentTaskIdIsAutoGenerated() {
        tools.createChannel("a2a-send-5", "Test", "APPEND", null, null, null, null, null, null);

        String returnedId = given()
                .urlEncodingEnabled(false)
                .contentType("application/json")
                .body(sendBody("a2a-send-5", "user", "auto id", null))
                .when().post(SEND_PATH)
                .then()
                .statusCode(200)
                .extract().path("task.id");

        assertNotNull(returnedId);
        assertDoesNotThrow(() -> UUID.fromString(returnedId),
                "auto-generated task id should be a valid UUID");
    }

    // -----------------------------------------------------------------------
    // Integration — message actually created in channel
    // -----------------------------------------------------------------------

    @Test
    void sendCreatesMessageInChannel() {
        tools.createChannel("a2a-send-6", "Test", "APPEND", null, null, null, null, null, null);

        given()
                .urlEncodingEnabled(false)
                .contentType("application/json")
                .body(sendBody("a2a-send-6", "user", "hello from a2a", null))
                .when().post(SEND_PATH)
                .then()
                .statusCode(200);

        // Message should be retrievable via check_messages
        QhorusMcpTools.CheckResult check = tools.checkMessages("a2a-send-6", 0L, 10, null, null, null);
        assertEquals(1, check.messages().size(), "A2A send should create exactly one message");
        assertEquals("hello from a2a", check.messages().get(0).content());
    }

    @Test
    void sendMessageTypeIsRequest() {
        tools.createChannel("a2a-send-7", "Test", "APPEND", null, null, null, null, null, null);

        given()
                .urlEncodingEnabled(false)
                .contentType("application/json")
                .body(sendBody("a2a-send-7", "user", "content", null))
                .when().post(SEND_PATH)
                .then()
                .statusCode(200);

        QhorusMcpTools.CheckResult check = tools.checkMessages("a2a-send-7", 0L, 10, null, null, null);
        assertEquals("QUERY", check.messages().get(0).messageType(),
                "A2A messages should be of type QUERY");
    }

    @Test
    void senderIsSetFromRoleField() {
        tools.createChannel("a2a-send-8", "Test", "APPEND", null, null, null, null, null, null);

        given()
                .urlEncodingEnabled(false)
                .contentType("application/json")
                .body(sendBody("a2a-send-8", "orchestrator", "task", null))
                .when().post(SEND_PATH)
                .then()
                .statusCode(200);

        QhorusMcpTools.CheckResult check = tools.checkMessages("a2a-send-8", 0L, 10, null, null, null);
        assertEquals("orchestrator", check.messages().get(0).sender(),
                "sender should be taken from message.role");
    }

    @Test
    void correlationIdSetOnCreatedMessage() {
        tools.createChannel("a2a-send-9", "Test", "APPEND", null, null, null, null, null, null);
        String taskId = UUID.randomUUID().toString();

        given()
                .urlEncodingEnabled(false)
                .contentType("application/json")
                .body(sendBody("a2a-send-9", "user", "correlated", taskId))
                .when().post(SEND_PATH)
                .then()
                .statusCode(200);

        QhorusMcpTools.CheckResult check = tools.checkMessages("a2a-send-9", 0L, 10, null, null, null);
        assertEquals(taskId, check.messages().get(0).correlationId(),
                "correlation_id on the message should equal the provided taskId");
    }

    // -----------------------------------------------------------------------
    // End-to-end — full A2A lifecycle: send → verify via check_messages
    // -----------------------------------------------------------------------

    @Test
    void e2eA2ASendThenCheckMessages() {
        tools.createChannel("a2a-e2e-send-1", "Test", "APPEND", null, null, null, null, null, null);
        String taskId = UUID.randomUUID().toString();

        // 1. External orchestrator sends via A2A
        String returnedTaskId = given()
                .urlEncodingEnabled(false)
                .contentType("application/json")
                .body(sendBody("a2a-e2e-send-1", "external-orchestrator", "do this work", taskId))
                .when().post(SEND_PATH)
                .then()
                .statusCode(200)
                .body("task.status.state", equalTo("submitted"))
                .extract().path("task.id");

        assertEquals(taskId, returnedTaskId);

        // 2. Internal agent picks up the message via MCP
        QhorusMcpTools.CheckResult check = tools.checkMessages("a2a-e2e-send-1", 0L, 10, null, null, null);
        assertEquals(1, check.messages().size());
        assertEquals("do this work", check.messages().get(0).content());
        assertEquals(taskId, check.messages().get(0).correlationId());
        assertEquals("external-orchestrator", check.messages().get(0).sender());
    }

    // -----------------------------------------------------------------------
    // Error cases — 400 for missing required fields
    // -----------------------------------------------------------------------

    @Test
    void missingContextIdReturns400() {
        given()
                .urlEncodingEnabled(false)
                .contentType("application/json")
                .body("{\"message\":{\"role\":\"user\",\"parts\":[{\"kind\":\"text\",\"text\":\"hi\"}]}}")
                .when().post(SEND_PATH)
                .then()
                .statusCode(400);
    }

    @Test
    void channelNotFoundReturns400() {
        given()
                .urlEncodingEnabled(false)
                .contentType("application/json")
                .body(sendBody("nonexistent-channel-xyz", "user", "hi", null))
                .when().post(SEND_PATH)
                .then()
                .statusCode(400);
    }

    @Test
    void missingPartsReturns400() {
        given()
                .urlEncodingEnabled(false)
                .contentType("application/json")
                .body("{\"message\":{\"role\":\"user\",\"contextId\":\"ch\",\"parts\":[]}}")
                .when().post(SEND_PATH)
                .then()
                .statusCode(400);
    }

    @Test
    void nullMessageReturns400() {
        given()
                .urlEncodingEnabled(false)
                .contentType("application/json")
                .body("{}")
                .when().post(SEND_PATH)
                .then()
                .statusCode(400);
    }
}
